; Example project using SIC as a PlatformIO library
[env:cardputer-io-stable]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_unflags =
build_flags =
  -DSIC_TARGET_CARDPUTER=1
  -DI2C_SDA_PIN=41
  -DI2C_SCL_PIN=42
  -DMIC_DATA=46
  -DMIC_CLK=43
  -DIR_TX_PIN=44
  ; Add your battery + keyboard flags if needed
lib_deps =
  ; The SIC library is in the parent folder when used locally; when published, specify its name here.